/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_AHB2ENR ((volatile uint32_t*) 0x44020C8C)
#define GPIOF_MODER ((volatile uint32_t*) 0x42021400)
#define GPIOF_ODR ((volatile uint32_t*) 0x42021414)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	*RCC_AHB2ENR |= (1 << 5);
	*GPIOF_MODER &= ~(3 << 8);
	*GPIOF_MODER |= (1 << 8);

	while(1){//YIEKESS
		*GPIOF_ODR |= (1 << 4);
		for (volatile int i = 0; i < 1000; i++);
		*GPIOF_ODR &= ~(1 << 4);
		for (volatile int i = 0; i < 1000; i++);
	}


}

